FROM rust:1 AS builder
WORKDIR /usr/src/app
COPY . .
RUN --mount=type=cache,target=/usr/src/app/target \
    --mount=type=cache,target=/usr/local/cargo/registry \
    cargo install --path . --bin other

FROM debian:stable-slim
# RUN apt-get update && apt-get install -y extra-runtime-dependencies && rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/local/cargo/bin/other /usr/local/bin/
CMD ["other"]
