name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    uses: ./.github/workflows/docker-reusable.yml
    with:
      image_name: samply/rust-test-repo-for-new-ci
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
