name: Docker

on:
  # Uncomment to enable nightly builds
  # schedule:
  #   - cron: 0 0 * * *
  push:
    branches:
      - main
      - develop
    tags:
      - v*.*.*
  pull_request:

jobs:
  docker:
    uses: ./.github/workflows/samply-docker.yml
    with:
      image_name: samply/rust-test-repo-for-new-ci
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
